# Generated by Django 6.0.5 on 2026-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=200)),
                ('order_id', models.CharField(blank=True, default='', max_length=200)),
                ('courier', models.CharField(blank=True, choices=[('', 'Unknown'), ('amazon', 'Amazon'), ('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('ekart', 'Ekart'), ('xpressbees', 'Xpressbees'), ('dtdc', 'DTDC'), ('shadowfax', 'Shadowfax'), ('other', 'Other')], default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
