# Generated by Django 6.0.5 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagescan',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagescan',
            name='notes',
            field=models.CharField(blank=True, choices=[('no_damage', 'No Damage'), ('damaged', 'Damaged')], default='', max_length=50),
        ),
    ]
