# Generated by Django 6.0.5 on 2026-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_packagescan_driver_name_alter_packagescan_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagescan',
            name='courier',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('amazon', 'Amazon'), ('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('ekart', 'Ekart'), ('xpressbees', 'Xpressbees'), ('dtdc', 'DTDC'), ('shadowfax', 'Shadowfax'), ('other', 'Other')], default='Amazon', max_length=50),
        ),
        migrations.AlterField(
            model_name='packagescan',
            name='notes',
            field=models.CharField(choices=[('Good condition', 'Good condition'), ('Damage', 'Damage')], default='Good condition', max_length=50),
        ),
    ]
